travis:
  secure:
    BINSTAR_TOKEN: qLSs2j7RhXbed3h0CuYQds4GPlpoWT+jil/E0A80k0j6O6OxTkhK/p9ur2c6aFDWQYGsf84DjdPw+xBSZaXdyz59yNiwHQQLYi6XHs2BMvcHWijsHGE7v2Hfj0h1l6gEoWIsPZTnJvSieyYkyYCjZ3n61+oWkfwUXoNbCru+BimFDTsFC1VLo+wgq5wOjEcwzx3aCozFV6RPOgzseNOmtETRXuQaqaN554RUQnrEiXa83+XNV1Rd46nyluzh5rJTJYTrZyHDw50WNrB9ZUF4Q3PoKW2nB5u0/KIL43pGZkuCSUNU4gDpQASHtaWyuLNtIIa90sKVMCcXuErO70/q+4F238WZEJ8mYrRUZoLDvzFEeOE4HOT43T5ulO92RiB8YstzogqZDVJ3Zs1VqrLxkaih+z2aegH3ZIGHNNH3NvIbu4WRCGTSW8YQ0LAVIRHraZDlX9O1ZlI8b7nOKz2gsPKl+/UjnuRdSvqf3YTq32gd5EQH90r98+7OLIU7lFpngjVkUkRzwOMiUJmmCfGwcLhVJpAlABoHaAAhRJLG81Ak6wYQoU4n9ROnpAq/0mw3YGBcz8ZuWeT8L4c8KqWoP44vW4NJLiAirTnIrcGuLExCNijQ3iHfBc/GsZIz9Q7HAY8RnQ3ZGu1yl5Wa/CFCyDxYR/Y6aa1s9Dchqp+05nI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
